### ISSUE TITLE
Funnel doesn´t work when all values are the same or too close

### ISSUE THREAD

**Issue by eduardoconviso** [lastboy/funnel-graph-js#17]
I have a funnel with 5 lanes. Somehow, when all the values are the same or really close,  the lanes disappear, showing only a big path of the last lane.

e.g.:

All ones: 

[
      [1, 1, 1, 1, 1],
      [1, 1, 1, 1, 1],
      [1, 1, 1, 1, 1],
      [1, 1, 1, 1, 1],
    ]

![image](https://github.com/user-attachments/assets/5595e696-3506-47a1-b4ac-47238dbc52a2)

I discovered this by having the following values:

[
    [
        42715,
        41395,
        41087,
        41224,
        41266
    ],
    [
        42714,
        41395,
        41087,
        41223,
        41266
    ],
    [
        42714,
        41395,
        41087,
        41223,
        41266
    ],
    [
        42714,
        41395,
        41087,
        41223,
        41266
    ]
]

You can check this fork of the CodePen: https://codepen.io/eduardodeasousa/pen/poMdKqw

**Comment by lastboy** [comment]
Thank you for raising this issue. I'm aware of it and will address it in upcoming releases.

**Comment by eduardoconviso** [comment]
Any roadmap on this?

**Comment by lastboy** [comment]
I tested some more datasets and I can see still issues with drawing the path

**Comment by lastboy** [comment]
Yes, I'm aware of that issue and I also reopened your issue.
I made a lot of good changes and fixes that will be publish today.
see: https://github.com/lastboy/funnel-graph-js/issues/22
